config/routes.rb
Rails.application.routes.draw do
  resources :miccroposts
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/miccropost.rb
class Miccropost < ApplicationRecord
  belongs_to :user
  validates :content, length: { maximum: 140},
        presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :miccroposts
  validates :name, presence: true    # 「FILL_IN」をコードに置き換えてください
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render html: "hello, world"    
  end
end

app/controllers/miccroposts_controller.rb
class MiccropostsController < ApplicationController
  before_action :set_miccropost, only: [:show, :edit, :update, :destroy]

  # GET /miccroposts
  # GET /miccroposts.json
  def index
    @miccroposts = Miccropost.all
  end

  # GET /miccroposts/1
  # GET /miccroposts/1.json
  def show
  end

  # GET /miccroposts/new
  def new
    @miccropost = Miccropost.new
  end

  # GET /miccroposts/1/edit
  def edit
  end

  # POST /miccroposts
  # POST /miccroposts.json
  def create
    @miccropost = Miccropost.new(miccropost_params)

    respond_to do |format|
      if @miccropost.save
        format.html { redirect_to @miccropost, notice: 'Miccropost was successfully created.' }
        format.json { render :show, status: :created, location: @miccropost }
      else
        format.html { render :new }
        format.json { render json: @miccropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /miccroposts/1
  # PATCH/PUT /miccroposts/1.json
  def update
    respond_to do |format|
      if @miccropost.update(miccropost_params)
        format.html { redirect_to @miccropost, notice: 'Miccropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @miccropost }
      else
        format.html { render :edit }
        format.json { render json: @miccropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /miccroposts/1
  # DELETE /miccroposts/1.json
  def destroy
    @miccropost.destroy
    respond_to do |format|
      format.html { redirect_to miccroposts_url, notice: 'Miccropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_miccropost
      @miccropost = Miccropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def miccropost_params
      params.require(:miccropost).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miccroposts_helper.rb
module MiccropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/miccroposts/_form.html.erb
<%= form_with(model: miccropost, local: true) do |form| %>
  <% if miccropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(miccropost.errors.count, "error") %> prohibited this miccropost from being saved:</h2>

      <ul>
      <% miccropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :miccropost_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :miccropost_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/miccroposts/edit.html.erb
<h1>Editing Miccropost</h1>

<%= render 'form', miccropost: @miccropost %>

<%= link_to 'Show', @miccropost %> |
<%= link_to 'Back', miccroposts_path %>

app/views/miccroposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Miccroposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @miccroposts.each do |miccropost| %>
      <tr>
        <td><%= miccropost.content %></td>
        <td><%= miccropost.user_id %></td>
        <td><%= link_to 'Show', miccropost %></td>
        <td><%= link_to 'Edit', edit_miccropost_path(miccropost) %></td>
        <td><%= link_to 'Destroy', miccropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Miccropost', new_miccropost_path %>

app/views/miccroposts/new.html.erb
<h1>New Miccropost</h1>

<%= render 'form', miccropost: @miccropost %>

<%= link_to 'Back', miccroposts_path %>

app/views/miccroposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @miccropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @miccropost.user_id %>
</p>

<%= link_to 'Edit', edit_miccropost_path(@miccropost) %> |
<%= link_to 'Back', miccroposts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>Miccropost:</strong>
  <%= @user.miccroposts %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>